
version: '3.5'

services:
  api:
    build: './api'
    ports:
      - 3000:3000
    command: ["/bin/bash", "server/start.sh"]

  ui:
    build: ./ui
    ports:
      - 80:80
    links:
      - api
    depends_on:
      - api
    environment:
      - REACT_APP_API_PORT=3000
    command: serve -s build -l tcp://0.0.0.0:80
